const fs = require('fs');
const path = require('path');

const fr = {
  welcome: {
    tag: "Pour les gérants de café",
    hero_title: "Gérez votre café. Pas l'inverse.",
    hero_subtitle: "Commandes, équipe et statistiques — dans une seule application simple.",
    start_free: "Commencer gratuitement",
    proof_1: "⚡ Configuration en 5 minutes",
    proof_2: "📊 Suivi en temps réel",
    proof_3: "☕ Conçu pour la réalité",
    feat1_title: "Gérez les commandes",
    feat1_desc: "Suivez chaque table en temps réel",
    feat2_title: "Statistiques en direct",
    feat2_desc: "Identifiez les heures de pointe et les meilleures ventes",
    feat3_title: "Synchronisez l'équipe",
    feat3_desc: "Moins d'erreurs, plus de fluidité",
    made_for_you: "Conçu pour les propriétaires de cafés marocains qui veulent du contrôle sans la complexité.",
    cta_title: "Votre café, nouvelle génération.",
    get_early_access: "Accès anticipé",
    login: "Se connecter",
  },
  common: {
    continue: "Continuer",
    back: "Retour",
    next: "Suivant",
    finish: "Terminer",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    copy: "Copier",
    loading: "Chargement...",
    success: "Succès",
    error: "Erreur",
    search: "Rechercher",
    all: "Tous",
    none: "Aucun",
    today: "Aujourd'hui",
    yesterday: "Hier",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois",
    confirm: "Confirmer",
    no_results: "Aucun résultat pour",
    apply: "Appliquer",
    filters: "Filtres",
    offline: "Hors ligne - En attente de connexion",
    access_denied: "Accès refusé",
    offline_queued: "Mode hors ligne. L'action est mise en file d'attente.",
    online_syncing: "Connexion rétablie. Les données sont en cours de synchronisation...",
    something_went_wrong: "Une erreur est survenue",
    error_boundary_title: "Interruption inattendue",
    error_boundary_subtitle: "L'application a rencontré un problème d'affichage. Vos données en cours et la file d'attente hors ligne sont préservées en toute sécurité.",
    reload_app: "Recharger l'application",
    back_to_dashboard: "Retour à l'accueil",
    technical_details: "Détails techniques",
    offline_data_safe: "Données et file d'attente hors ligne sécurisées",
  },
  auth: {
    subtitle: "Gérez votre café intelligemment",
    owner: "Gérant",
    staff: "Personnel",
    email: "Email",
    password: "Mot de passe",
    login: "Se connecter",
    register: "S'inscrire",
    no_account: "Pas encore de compte ? ",
    register_link: "Créer un compte",
    already_account: "Déjà un compte ? ",
    login_link: "Se connecter",
    cafe_code: "Code du café",
    cafe_code_hint: "Demandez ce code à votre gérant",
    your_name: "Votre prénom",
    pin_incorrect: "Code PIN incorrect",
    code_incorrect: "Code incorrect",
    logout_confirm: "Êtes-vous sûr de vouloir vous déconnecter ?",
    offline_unrecognized_code: "Vous êtes hors-ligne et ce code n'est pas reconnu localement.",
    staff_error: "Erreur personnel: ",
    no_active_staff: "Aucun employé actif trouvé pour ce café.",
    login_error_prefix: "Erreur: ",
    offline_first_login_required: "Une première connexion en ligne sur cet appareil est requise.",
    offline_session_expired: "Session hors ligne expirée. Veuillez vous reconnecter en ligne."
  },
  wizard: {
    step1: {
      title: "Parlons de votre café",
      subtitle: "Ces informations apparaîtront sur vos bilans",
    },
    step2: {
      title: "Configuration des tarifs",
      subtitle: "Vous pourrez modifier ces valeurs plus tard",
    },
    step3: {
      title: "Ajouter un employé",
      subtitle: "Vous pouvez aussi le faire plus tard",
    },
    step4: {
      title: "Votre café est configuré !",
    },
    finish: "Commencer à utiliser Nook OS",
    code_copied: "Code copié",
  },
  dashboard: {
    revenue_today: "Aujourd'hui",
    active_sessions: "Sessions actives",
    no_active_sessions: "Aucune session active",
    start_session: "Nouvelle session",
    quick_actions: "Actions rapides",
    history: "Historique",
    clients: "Clients",
    reports: "Bilan",
    last_sessions: "Dernières sessions",
    access_denied: "Accès refusé",
  },
  sessions: {
    new: "Nouvelle session",
    client: "Client",
    place: "Place",
    rate: "Tarif",
    notes: "Notes",
    start: "Démarrer la session",
    end: "Clôturer",
    duration: "durée",
    amount: "montant",
    extras: "Consommations",
    add_extra: "Ajouter un article",
    payment_method: "Mode de paiement",
    cash: "Espèces",
    card: "Carte",
    account: "Compte",
    free: "Gratuit",
    received: "Montant reçu",
    change: "Monnaie à rendre",
    seat_taken: "Cette place est déjà occupée",
    session_started_seat: "Session démarrée — Place {{seat}}",
    session_not_found: "Session non trouvée",
    extras_added: "Consommations ajoutées",
    item_deleted: "Article supprimé",
    session_closed_amount: "Session clôturée — {{amount}} DH",
  },
  clients: {
    title: "Clients",
    new: "Nouveau compte client",
    balance: "solde",
    recharge: "Recharger",
    visits: "visites",
    spent: "dépensé",
    member_since: "Membre depuis",
    client_created: "Compte client créé",
  },
  reports: {
    title: "Bilans",
    revenue: "Chiffre d'affaires",
    sessions: "sessions",
    avg_duration: "min moy",
    payment_breakdown: "Répartition par paiement",
    busiest_hours: "Heures d'affluence",
    export_pdf: "Exporter en PDF",
    total: "Total",
    average: "Moyenne",
    custom_date: "Date personnalisée",
    search_placeholder: "Rechercher un client ou une place...",
    no_sessions: "Aucune session trouvée",
  },
  cat: {
    boisson: "Boissons",
    nourriture: "Nourriture",
    autre: "Autre",
  },
  settings: {
    title: "Paramètres",
    my_cafe: "Mon café",
    rates: "Tarifs",
    alerts: "Alertes",
    products: "Produits & extras",
    team: "Mon équipe",
    invite_code: "Code d'invitation",
    language: "Language / Langue",
    account: "Compte",
    logout: "Se déconnecter",
    product_catalog: "Catalogue Produits",
    search_product: "Rechercher un produit...",
    add_product: "Nouveau produit",
    product_name: "Nom du produit",
    price: "Prix (DH)",
    category: "Catégorie",
    active_product: "Produit actif",
    add_to_catalog: "Ajouter au catalogue",
    delete_product: "Supprimer le produit ?",
    delete_product_confirm: "Voulez-vous vraiment supprimer",
    no_products: "Aucun produit trouvé",
    product_added: "Produit ajouté",
    product_deleted: "Produit supprimé",
    product_activated: "Produit activé",
    product_deactivated: "Produit désactivé",
    product_updated: "Produit modifié",
    audit_log: "Journal d'audit",
    info_updated: "Informations mises à jour",
    rates_updated: "Tarifs mis à jour",
    logo_saved: "Logo enregistré",
    logo_deleted: "Logo supprimé",
    code_copied: "Code copié",
  },
  audit: {
    search_placeholder: "Rechercher dans les journaux...",
    no_logs: "Aucun journal trouvé",
    session_started: "Session démarrée",
    session_closed: "Session clôturée",
    extras_added: "Consommations ajoutées",
    client_recharged: "Compte client rechargé",
    staff_created: "Employé créé",
    staff_deleted: "Employé supprimé",
    staff_updated: "Employé mis à jour",
    product_added: "Produit ajouté",
    product_deleted: "Produit supprimé",
    product_updated: "Produit modifié",
    cafe_updated: "Café mis à jour",
  },
  staff: {
    title: "Mon équipe",
    add: "Nouvel employé",
    name: "Nom de l'employé",
    pin_setup: "Mot de passe (4 chiffres)",
    confirm_pin: "Confirmer le mot de passe",
    new_pin: "Nouveau mot de passe (optionnel)",
    permissions: "Droits d'accès",
    perm_sessions: "Gérer les sessions",
    perm_reports: "Voir les rapports",
    perm_clients: "Gérer les clients",
    perm_settings: "Paramètres",
    perm_rates: "Modifier les tarifs",
    create: "Créer l'employé",
    save: "Enregistrer les modifications",
    active: "Actif",
    inactive: "Inactif",
    account_active: "Compte Actif",
    account_inactive: "Compte Inactif",
    can_login: "L'employé peut se connecter",
    cannot_login: "L'employé ne peut plus se connecter",
    delete: "Supprimer",
    delete_confirm: "Voulez-vous vraiment supprimer",
    change_pin: "Modifier le mot de passe",
    always_on: "Toujours activé",
    search_placeholder: "Rechercher un employé...",
    no_staff: "Aucun employé ajouté",
    no_results: "Aucun employé ne correspond à votre recherche",
    staff_added: "Employé ajouté",
    staff_deleted: "Employé supprimé",
    staff_updated: "Employé mis à jour",
    staff_activated: "Employé activé",
    staff_deactivated: "Employé désactivé",
    edit_staff: "Modifier l'employé",
    delete_staff: "Supprimer l'employé ?",
    deleting: "Suppression...",
    activate: "Activer",
    deactivate: "Désactiver",
  },
};

const en = {
  welcome: {
    tag: "For Cafe Owners",
    hero_title: "Run your café. Not after it.",
    hero_subtitle: "Orders, staff, and insights — all in one simple app.",
    start_free: "Start Free",
    proof_1: "⚡ Set up in 5 minutes",
    proof_2: "📊 Track everything live",
    proof_3: "☕ Built for real cafés",
    feat1_title: "Manage Orders",
    feat1_desc: "See every order in real time",
    feat2_title: "Know What Sells",
    feat2_desc: "Track best drinks & peak hours",
    feat3_title: "Sync Your Team",
    feat3_desc: "No confusion, no shouting",
    made_for_you: "Built for Moroccan café owners who want control without complexity.",
    cta_title: "Your café, upgraded.",
    get_early_access: "Get Early Access",
    login: "Login",
  },
  common: {
    continue: "Continue",
    back: "Back",
    next: "Next",
    finish: "Finish",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    copy: "Copy",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    search: "Search",
    all: "All",
    none: "None",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This week",
    thisMonth: "This month",
    confirm: "Confirm",
    no_results: "No results found for",
    apply: "Apply",
    filters: "Filters",
    offline: "Offline - Waiting for connection",
    access_denied: "Access denied",
    offline_queued: "Offline mode. Action queued.",
    online_syncing: "Connection restored. Data is syncing...",
    something_went_wrong: "Something went wrong",
    error_boundary_title: "Unexpected Interruption",
    error_boundary_subtitle: "The application encountered a display error. Your active session data and offline queue remain safely preserved.",
    reload_app: "Reload Application",
    back_to_dashboard: "Return to Home",
    technical_details: "Technical Details",
    offline_data_safe: "Offline queue & data preserved safely",
  },
  auth: {
    subtitle: "Manage your cafe smartly",
    owner: "Owner",
    staff: "Staff",
    email: "Email",
    password: "Password",
    login: "Login",
    register: "Register",
    no_account: "No account yet? ",
    register_link: "Create an account",
    already_account: "Already have an account? ",
    login_link: "Login",
    cafe_code: "Cafe code",
    cafe_code_hint: "Ask your manager for this code",
    your_name: "Your name",
    pin_incorrect: "Incorrect Password",
    code_incorrect: "Incorrect code",
    logout_confirm: "Are you sure you want to logout?",
    offline_unrecognized_code: "You are offline and this code is not recognized locally.",
    staff_error: "Staff error: ",
    no_active_staff: "No active staff found for this cafe.",
    login_error_prefix: "Error: ",
    offline_first_login_required: "An initial online login on this device is required.",
    offline_session_expired: "Offline session expired. Please reconnect online."
  },
  wizard: {
    step1: {
      title: "Let's talk about your cafe",
      subtitle: "This information will appear on your reports",
    },
    step2: {
      title: "Rate configuration",
      subtitle: "You can change these values later",
    },
    step3: {
      title: "Add an employee",
      subtitle: "You can also do this later",
    },
    step4: {
      title: "Your cafe is configured!",
    },
    finish: "Start using Nook OS",
    code_copied: "Code copied",
  },
  dashboard: {
    revenue_today: "Today",
    active_sessions: "Active sessions",
    no_active_sessions: "No active sessions",
    start_session: "New session",
    quick_actions: "Quick actions",
    history: "History",
    clients: "Clients",
    reports: "Report",
    last_sessions: "Last sessions",
    access_denied: "Access denied",
  },
  sessions: {
    new: "New session",
    client: "Client",
    place: "Seat",
    rate: "Rate",
    notes: "Notes",
    start: "Start session",
    end: "End session",
    duration: "duration",
    amount: "amount",
    extras: "Extras",
    add_extra: "Add extra",
    payment_method: "Payment method",
    cash: "Cash",
    card: "Card",
    account: "Account",
    free: "Free",
    received: "Amount received",
    change: "Change to return",
    seat_taken: "This seat is already occupied",
    session_started_seat: "Session started — Seat {{seat}}",
    session_not_found: "Session not found",
    extras_added: "Extras added",
    item_deleted: "Item deleted",
    session_closed_amount: "Session closed — {{amount}} DH",
  },
  clients: {
    title: "Clients",
    new: "New client account",
    balance: "balance",
    recharge: "Recharge",
    visits: "visits",
    spent: "spent",
    member_since: "Member since",
    client_created: "Client account created",
  },
  reports: {
    title: "Reports",
    revenue: "Revenue",
    sessions: "sessions",
    avg_duration: "avg min",
    payment_breakdown: "Payment breakdown",
    busiest_hours: "Busiest hours",
    export_pdf: "Export to PDF",
    total: "Total",
    average: "Average",
    custom_date: "Custom date",
    search_placeholder: "Search for a client or seat...",
    no_sessions: "No sessions found",
  },
  cat: {
    boisson: "Drinks",
    nourriture: "Food",
    autre: "Other",
  },
  settings: {
    title: "Settings",
    my_cafe: "My cafe",
    rates: "Rates",
    alerts: "Alerts",
    products: "Products & extras",
    team: "My team",
    invite_code: "Invite code",
    language: "Language",
    account: "Account",
    logout: "Logout",
    product_catalog: "Product Catalog",
    search_product: "Search for a product...",
    add_product: "New product",
    product_name: "Product name",
    price: "Price (DH)",
    category: "Category",
    active_product: "Active product",
    add_to_catalog: "Add to catalog",
    delete_product: "Delete product?",
    delete_product_confirm: "Are you sure you want to delete",
    no_products: "No products found",
    product_added: "Product added",
    product_deleted: "Product deleted",
    product_activated: "Product activated",
    product_deactivated: "Product deactivated",
    product_updated: "Product updated",
    audit_log: "Audit Log",
    info_updated: "Information updated",
    rates_updated: "Rates updated",
    logo_saved: "Logo saved",
    logo_deleted: "Logo deleted",
    code_copied: "Code copied",
  },
  audit: {
    search_placeholder: "Search logs...",
    no_logs: "No logs found",
    session_started: "Session started",
    session_closed: "Session closed",
    extras_added: "Extras added",
    client_recharged: "Client account recharged",
    staff_created: "Staff created",
    staff_deleted: "Staff deleted",
    staff_updated: "Staff updated",
    product_added: "Product added",
    product_deleted: "Product deleted",
    product_updated: "Product updated",
    cafe_updated: "Cafe updated",
  },
  staff: {
    title: "My team",
    add: "New staff",
    name: "Staff name",
    pin_setup: "Password (4 digits)",
    confirm_pin: "Confirm Password",
    new_pin: "New Password (optional)",
    permissions: "Access rights",
    perm_sessions: "Manage sessions",
    perm_reports: "View reports",
    perm_clients: "Manage clients",
    perm_settings: "Settings",
    perm_rates: "Change rates",
    create: "Create staff",
    save: "Save changes",
    active: "Active",
    inactive: "Inactive",
    account_active: "Active Account",
    account_inactive: "Inactive Account",
    can_login: "Staff can login",
    cannot_login: "Staff cannot login anymore",
    delete: "Delete",
    delete_confirm: "Are you sure you want to delete",
    change_pin: "Change Password",
    always_on: "Always on",
    search_placeholder: "Search for staff...",
    no_staff: "No staff added",
    no_results: "No staff matches your search",
    staff_added: "Staff added",
    staff_deleted: "Staff deleted",
    staff_updated: "Staff updated",
    staff_activated: "Staff activated",
    staff_deactivated: "Staff deactivated",
    edit_staff: "Edit staff",
    delete_staff: "Delete staff?",
    deleting: "Deleting...",
    activate: "Activate",
    deactivate: "Deactivate",
  },
};

const ar = {
  welcome: {
    tag: "لأصحاب المقاهي",
    hero_title: "سيّر المقهى ديالك. ماشي هو اللي يسيّرك.",
    hero_subtitle: "الطلبات، الموظفين، والإحصائيات — كلشي فبرنامج واحد ساهل.",
    start_free: "ابدا فابور",
    proof_1: "⚡ الإعداد فـ 5 دقايق",
    proof_2: "📊 تتبع كلشي فالحين",
    proof_3: "☕ مصمم للمقاهي الحقيقية",
    feat1_title: "تسيير الطلبات",
    feat1_desc: "تبع كل طلبة فالحين",
    feat2_title: "الإحصائيات المباشرة",
    feat2_desc: "عرف شنو كيتباع وأوقات الذروة",
    feat3_title: "نظم فريقك",
    feat3_desc: "نقص الأخطاء وزيد فالسلاسة",
    made_for_you: "مصمم لأصحاب المقاهي المغاربة اللي بغاو التحكم بلا تعقيد.",
    cta_title: "المقهى ديالك، الجيل الجديد.",
    get_early_access: "تسجيل مبكر",
    login: "تسجيل الدخول",
  },
  common: {
    continue: "متابعة",
    back: "رجوع",
    next: "التالي",
    finish: "إنهاء",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    copy: "نسخ",
    loading: "جاري التحميل...",
    success: "نجاح",
    error: "خطأ",
    search: "بحث",
    all: "الكل",
    none: "لا شيء",
    today: "اليوم",
    yesterday: "البارح",
    thisWeek: "هاد السيمانة",
    thisMonth: "هاد الشهر",
    confirm: "تأكيد",
    no_results: "لا توجد نتائج لـ",
    apply: "تطبيق",
    filters: "تصفية",
    offline: "بدون اتصال - في انتظار الشبكة",
    access_denied: "مرفوض",
    offline_queued: "وضع عدم الاتصال. تمت إضافة العملية للانتظار.",
    online_syncing: "تمت استعادة الاتصال. جاري المزامنة...",
    something_went_wrong: "حدث خطأ غير متوقع",
    error_boundary_title: "انقطاع غير متوقع",
    error_boundary_subtitle: "واجه التطبيق مشكلة في العرض. تبقى بيانات الجلسات وقائمة العمليات غير المتصلة محفوظة بأمان تام.",
    reload_app: "إعادة تحميل التطبيق",
    back_to_dashboard: "العودة للرئيسية",
    technical_details: "التفاصيل التقنية",
    offline_data_safe: "البيانات وقائمة الانتظار محفوظة بأمان",
  },
  auth: {
    subtitle: "سيّر المقهى ديالك بذكاء",
    owner: "المدير",
    staff: "الموظف",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    login: "دخول",
    register: "تسجيل حساب",
    no_account: "مازال ماعندكش حساب؟ ",
    register_link: "إنشاء حساب",
    already_account: "عندك حساب؟ ",
    login_link: "تسجيل الدخول",
    cafe_code: "رمز المقهى",
    cafe_code_hint: "طلب الرمز من المدير ديالك",
    your_name: "الاسم ديالك",
    pin_incorrect: "كلمة المرور غالطة",
    code_incorrect: "الرمز غير صحيح",
    logout_confirm: "واش متأكد بغيتي تخرج؟",
    offline_unrecognized_code: "أنت خارج التغطية وهذا الرمز غير معروف محليا.",
    staff_error: "خطأ في الموظف: ",
    no_active_staff: "لم يتم العثور على موظف نشط في هذا المقهى.",
    login_error_prefix: "خطأ: ",
    offline_first_login_required: "يلزم تسجيل الدخول عبر الإنترنت لأول مرة على هذا الجهاز.",
    offline_session_expired: "انتهت صلاحية الجلسة في وضع عدم الاتصال. يرجى الاتصال بالإنترنت مجددًا."
  },
  wizard: {
    step1: {
      title: "نهضرو على المقهى ديالك",
      subtitle: "هاد المعلومات غادي تبان فالتقارير",
    },
    step2: {
      title: "إعداد التسعيرة",
      subtitle: "تقدر تبدل هاد الأثمنة من بعد",
    },
    step3: {
      title: "إضافة موظف",
      subtitle: "تقدر تدير هادشي من بعد",
    },
    step4: {
      title: "المقهى ديالك واجد!",
    },
    finish: "بدا تخدم بـ Nook OS",
    code_copied: "تم نسخ الرمز",
  },
  dashboard: {
    revenue_today: "اليوم",
    active_sessions: "الجلسات النشطة",
    no_active_sessions: "مكاين حتى جلسة نشطة",
    start_session: "جلسة جديدة",
    quick_actions: "إجراءات سريعة",
    history: "السجل",
    clients: "الزبناء",
    reports: "التقرير",
    last_sessions: "آخر الجلسات",
    access_denied: "تم رفض الوصول",
  },
  sessions: {
    new: "جلسة جديدة",
    client: "الزبون",
    place: "البلاصة",
    rate: "التسعيرة",
    notes: "ملاحظات",
    start: "بدء الجلسة",
    end: "إنهاء",
    duration: "المدة",
    amount: "المبلغ",
    extras: "الطلبات",
    add_extra: "إضافة طلب",
    payment_method: "طريقة الأداء",
    cash: "نقداً",
    card: "بطاقة",
    account: "حساب",
    free: "فابور",
    received: "المبلغ المستلم",
    change: "الصرف",
    seat_taken: "هاد البلاصة عامرة",
    session_started_seat: "بدأت الجلسة — البلاصة {{seat}}",
    session_not_found: "الجلسة غير موجودة",
    extras_added: "تمت إضافة الطلبات",
    item_deleted: "تم حذف الطلب",
    session_closed_amount: "تم إنهاء الجلسة — {{amount}} درهم",
  },
  clients: {
    title: "الزبناء",
    new: "حساب زبون جديد",
    balance: "الرصيد",
    recharge: "تعبئة",
    visits: "الزيارات",
    spent: "المصروف",
    member_since: "عضو منذ",
    client_created: "تم إنشاء حساب الزبون",
  },
  reports: {
    title: "التقارير",
    revenue: "المداخيل",
    sessions: "جلسات",
    avg_duration: "متوسط الدقائق",
    payment_breakdown: "الأداء حسب الطريقة",
    busiest_hours: "أوقات الذروة",
    export_pdf: "استخراج PDF",
    total: "المجموع",
    average: "المتوسط",
    custom_date: "تاريخ مخصص",
    search_placeholder: "قلب على زبون أو بلاصة...",
    no_sessions: "مكاين حتى جلسة",
  },
  cat: {
    boisson: "مشروبات",
    nourriture: "مأكولات",
    autre: "أخرى",
  },
  settings: {
    title: "الإعدادات",
    my_cafe: "المقهى ديالي",
    rates: "التسعيرة",
    alerts: "التنبيهات",
    products: "المنتجات",
    team: "الفريق",
    invite_code: "رمز الدعوة",
    language: "اللغة",
    account: "الحساب",
    logout: "تسجيل الخروج",
    product_catalog: "قائمة المنتجات",
    search_product: "قلب على شي منتج...",
    add_product: "منتج جديد",
    product_name: "اسم المنتج",
    price: "الثمن (درهم)",
    category: "الفئة",
    active_product: "منتج مفعل",
    add_to_catalog: "إضافة للقائمة",
    delete_product: "حذف المنتج؟",
    delete_product_confirm: "واش متأكد بغيتي تحذف",
    no_products: "مكاين حتى منتج",
    product_added: "تمت إضافة المنتج",
    product_deleted: "تم حذف المنتج",
    product_activated: "تم تفعيل المنتج",
    product_deactivated: "تم تعطيل المنتج",
    product_updated: "تم تعديل المنتج",
    audit_log: "سجل العمليات",
    info_updated: "تم تحديث المعلومات",
    rates_updated: "تم تحديث الأثمنة",
    logo_saved: "تم حفظ الشعار",
    logo_deleted: "تم حذف الشعار",
    code_copied: "تم نسخ الرمز",
  },
  audit: {
    search_placeholder: "قلب فالسجل...",
    no_logs: "مكاين حتى سجل",
    session_started: "بدء الجلسة",
    session_closed: "إنهاء الجلسة",
    extras_added: "إضافة طلبات",
    client_recharged: "تعبئة حساب زبون",
    staff_created: "إضافة موظف",
    staff_deleted: "حذف موظف",
    staff_updated: "تعديل موظف",
    product_added: "إضافة منتج",
    product_deleted: "حذف منتج",
    product_updated: "تعديل منتج",
    cafe_updated: "تحديث المقهى",
  },
  staff: {
    title: "الفريق ديالي",
    add: "موظف جديد",
    name: "اسم الموظف",
    pin_setup: "كلمة المرور (4 أرقام)",
    confirm_pin: "تأكيد كلمة المرور",
    new_pin: "كلمة مرور جديدة (اختياري)",
    permissions: "صلاحيات الوصول",
    perm_sessions: "تسيير الجلسات",
    perm_reports: "رؤية التقارير",
    perm_clients: "تسيير الزبناء",
    perm_settings: "الإعدادات",
    perm_rates: "تعديل التسعيرة",
    create: "إضافة الموظف",
    save: "حفظ التغييرات",
    active: "نشط",
    inactive: "غير نشط",
    account_active: "حساب نشط",
    account_inactive: "حساب غير نشط",
    can_login: "يمكن للموظف الدخول",
    cannot_login: "لا يمكن للموظف الدخول",
    delete: "حذف",
    delete_confirm: "واش متأكد بغيتي تحذف",
    change_pin: "تغيير كلمة المرور",
    always_on: "دائما شغال",
    search_placeholder: "قلب على موظف...",
    no_staff: "مكاين حتى موظف",
    no_results: "مكاين حتى موظف بهاد المواصفات",
    staff_added: "تمت إضافة الموظف",
    staff_deleted: "تم حذف الموظف",
    staff_updated: "تم تعديل الموظف",
    staff_activated: "تم تفعيل الموظف",
    staff_deactivated: "تم تعطيل الموظف",
    edit_staff: "تعديل الموظف",
    delete_staff: "حذف الموظف؟",
    deleting: "جاري الحذف...",
    activate: "تفعيل",
    deactivate: "تعطيل",
  },
};

const fileContent = `
export const translations = {
  fr: ${JSON.stringify(fr, null, 4)},
  en: ${JSON.stringify(en, null, 4)},
  ar: ${JSON.stringify(ar, null, 4)}
};
`;

const targetFile = path.resolve(__dirname, '../src/i18n/translations.ts');
fs.writeFileSync(targetFile, fileContent.trim() + '\n');
console.log('✅ Updated translations in ' + targetFile);
